### ISSUE TITLE
DC2 Run 2.2i : need to set up the CC framework

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#126]
- [x] update the SRS pipeline : v3, completed dpdd stages, check new https underlying protocol (may need the schema path to be updated)
- [x] merge IPP branch to master
- [x] check status of DC2-production
- [x] try to use conda install instead of manual
- [x] ensure v18 with devtoolset-7 is usable : `/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v18.1.0-dev`

**Comment by johannct** [comment]
SRS pipeline update committed in d23d56cb6eb9298ae7cd9d77bca22ce2e5e31881

**Comment by johannct** [comment]
status report: pipeline functional, need a tag for DC2-production, a decision about the stack version (v18.1.0 and w44 both tested and result is a slightly different number of sources at calexp and coadd level), conda install is deferred and we are currently using a script https://github.com/LSSTDESC/ImageProcessingPipelines/blob/master/workflows/srs/env_config/setup_desc_drp.sh

**Comment by johannct** [comment]
status report : pull request open to get the right env_config for the Run2.2 production. A few remaining questions, and people called for resolution
- [] Pipeline does not include sim_ci_pipe. Should we? If yes, what frequency? @jchiang87 
- [] Pipeline does not include validate_drp since Nicolas' time. Should we reconsider it? @wmwv
- [] 8 mmag issue needs to be settled @katrinheitmann @jchiang87 
- [] refcat added columns need to be checked again wrt the new codebase @heather999 and @boutigny 
- [] write_gcr_to_parquet.py does the final DPDD minimal catalog writing.... but it cannot currently be used in the pipeline as it uses static reader's configs which by definition depend on configuration of the pipeline. This is probably directly related to the other issue of having gcr-catalogs easily configuration on other sites than NERSC. @wmwv @yymao

**Comment by heather999** [comment]
#134 is now closed after fresh reference catalog is now complete. Requesting #135 be merged to capture the new copy of the ingestReferenceCatalog config for Run2.2i, which is truly just a copy of the Run2.1 configuration.

**Comment by heather999** [comment]
The 8mmag issue is solved, right?  We have updated the config in obs_lsst dc2/run2.2 as discussed in #118

**Comment by johannct** [comment]
8mmag issue solved *for DC2 purposes* here : https://github.com/lsst/obs_lsst/commit/999dc00f53eef00a9981d6b1286016d2592fa0ff

**Comment by johannct** [comment]
I tagged IPP DC2-Run2.2i-1.0.0 to get ingest and calexp done

**Comment by johannct** [comment]
oldie and not goldie anymore
